### ISSUE TITLE
v3版本yunzai加载插件出现错误

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [Lumie-fx/ayaka-plugin#6]
可能是喵喵插件更新2.0的原因
更新后就报错了 求适配
![Screenshot_20220927-225555386.jpg](https://user-images.githubusercontent.com/86163024/192561696-831516ad-76f5-48ed-8f0d-5a742bb59da4.jpg)

**Comment by Lumie-fx** [comment]
啥时候更新的，我最近更新过一次以后没碰到这个问题啊。
看样子是喵喵文件结构改变了导致我这边引不到了，我看下。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lumie-fx/ayaka-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月27日(星期二) 晚上10:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Lumie-fx/ayaka-plugin] v3版本yunzai加载插件出现错误 (Issue #6)





 
可能是喵喵插件更新2.0的原因
 更新后就报错了 求适配

**Comment by YuYue-Amatsuki** [comment]
> 啥时候更新的，我最近更新过一次以后没碰到这个问题啊。
> 看样子是喵喵文件结构改变了导致我这边引不到了，我看下。
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "Lumie-fx/ayaka-plugin"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2022年9月27日(星期二) 晚上10:57
> ***@***.***&gt;;
> ***@***.***&gt;;
> 主题:&nbsp;[Lumie-fx/ayaka-plugin] v3版本yunzai加载插件出现错误 (Issue #6)
> 
> 
> 
> 
> 
>  
> 可能是喵喵插件更新2.0的原因
>  更新后就报错了 求适配
>  
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

就是今天早上喵喵插件更新2.0之后

**Comment by Lumie-fx** [comment]
更新一下，ok了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lumie-fx/ayaka-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月27日(星期二) 晚上11:03
***@***.***&gt;;
抄送:&nbsp;"stars ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lumie-fx/ayaka-plugin] v3版本yunzai加载插件出现错误 (Issue #6)





  
啥时候更新的，我最近更新过一次以后没碰到这个问题啊。
 看样子是喵喵文件结构改变了导致我这边引不到了，我看下。
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "Lumie-fx/ayaka-plugin"                                                                                    @.&gt;;
 发送时间:&nbsp;2022年9月27日(星期二) 晚上10:57
 @.&gt;;
 @.***&gt;;
 主题:&nbsp;[Lumie-fx/ayaka-plugin] v3版本yunzai加载插件出现错误 (Issue #6)
 
可能是喵喵插件更新2.0的原因
 更新后就报错了 求适配
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you are subscribed to this thread.Message ID: @.***&gt;
  
就是今天早上喵喵插件更新2.0之后

**Comment by YuYue-Amatsuki** [comment]
> 更新一下，ok了
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "Lumie-fx/ayaka-plugin"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2022年9月27日(星期二) 晚上11:03
> ***@***.***&gt;;
> 抄送:&nbsp;"stars ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [Lumie-fx/ayaka-plugin] v3版本yunzai加载插件出现错误 (Issue #6)
> 
> 
> 
> 
> 
>   
> 啥时候更新的，我最近更新过一次以后没碰到这个问题啊。
>  看样子是喵喵文件结构改变了导致我这边引不到了，我看下。
>  
> ------------------&nbsp;原始邮件&nbsp;------------------
>  发件人:                                                                                                                        "Lumie-fx/ayaka-plugin"                                                                                    @.&gt;;
>  发送时间:&nbsp;2022年9月27日(星期二) 晚上10:57
>  @.&gt;;
>  @.***&gt;;
>  主题:&nbsp;[Lumie-fx/ayaka-plugin] v3版本yunzai加载插件出现错误 (Issue #6)
>  
> 可能是喵喵插件更新2.0的原因
>  更新后就报错了 求适配
>  
> —
>  Reply to this email directly, view it on GitHub, or unsubscribe.
>  You are receiving this because you are subscribed to this thread.Message ID: @.***&gt;
>   
> 就是今天早上喵喵插件更新2.0之后
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

今天更新喵喵后又出现报错了 望适配
![Screenshot_20220929-131852_Microsoft_远程桌面.png](https://user-images.githubusercontent.com/86163024/192945245-2597651f-7875-4af4-ab22-2e5143e8d6fa.png)
